// AUTO-GENERATED by gen_resnet50_model.py — do not edit
// Model: torchvision_resnet50_imagenet_v1

#ifndef RESNET50_MODEL_CONSTANTS_H
#define RESNET50_MODEL_CONSTANTS_H

#include <stdint.h>

// ---- Model identity ----
#define RESNET50_MODEL_VARIANT  "torchvision_resnet50_imagenet_v1"
#define RESNET50_MODEL_INPUT_H  224
#define RESNET50_MODEL_INPUT_W  224
#define RESNET50_MODEL_INPUT_C  3
#define RESNET50_N_CLASSES      1000

// ---- BlockDialect parameters ----
#define BD_BLOCK_SIZE           32
#define BD_BLOCK_BYTES          18   /* 2-byte meta + 16-byte packed codes */
/* Biases stored as float32 in separate DTYPE_FLOAT32 tensor entries */

// ---- Flash / WeightStore layout ----
#define FLASH_WEIGHT_BASE       0x20000000u
// FLASH_WEIGHT_OFFSET is the raw SPI-flash byte offset where weights are programmed.
// The SoC flashOffset parameter already translates CPU 0x20000000 → flash 0x100000.
// Firmware must NOT add this to FLASH_WEIGHT_BASE.
#define FLASH_WEIGHT_OFFSET     0x00100000u  /* raw flash byte offset (for iceprog -o) */
#define WEIGHT_BLOB_ADDR        FLASH_WEIGHT_BASE  /* SoC window already starts at flash+FLASH_WEIGHT_OFFSET */

// ---- VWB2 blob sizes (bytes) ----
#define RESNET50_BD_BLOB_SIZE    14460412u

// ---- Layer count ----
#define RESNET50_N_LAYERS       54

// ---- Layer enum (matches VWB2 tensor table order) ----
typedef enum {
    RESNET50_LAYER_CONV1 = 0,
    RESNET50_LAYER_LAYER1_0_CONV1 = 1,
    RESNET50_LAYER_LAYER1_0_CONV2 = 2,
    RESNET50_LAYER_LAYER1_0_CONV3 = 3,
    RESNET50_LAYER_LAYER1_0_DOWNSAMPLE = 4,
    RESNET50_LAYER_LAYER1_1_CONV1 = 5,
    RESNET50_LAYER_LAYER1_1_CONV2 = 6,
    RESNET50_LAYER_LAYER1_1_CONV3 = 7,
    RESNET50_LAYER_LAYER1_2_CONV1 = 8,
    RESNET50_LAYER_LAYER1_2_CONV2 = 9,
    RESNET50_LAYER_LAYER1_2_CONV3 = 10,
    RESNET50_LAYER_LAYER2_0_CONV1 = 11,
    RESNET50_LAYER_LAYER2_0_CONV2 = 12,
    RESNET50_LAYER_LAYER2_0_CONV3 = 13,
    RESNET50_LAYER_LAYER2_0_DOWNSAMPLE = 14,
    RESNET50_LAYER_LAYER2_1_CONV1 = 15,
    RESNET50_LAYER_LAYER2_1_CONV2 = 16,
    RESNET50_LAYER_LAYER2_1_CONV3 = 17,
    RESNET50_LAYER_LAYER2_2_CONV1 = 18,
    RESNET50_LAYER_LAYER2_2_CONV2 = 19,
    RESNET50_LAYER_LAYER2_2_CONV3 = 20,
    RESNET50_LAYER_LAYER2_3_CONV1 = 21,
    RESNET50_LAYER_LAYER2_3_CONV2 = 22,
    RESNET50_LAYER_LAYER2_3_CONV3 = 23,
    RESNET50_LAYER_LAYER3_0_CONV1 = 24,
    RESNET50_LAYER_LAYER3_0_CONV2 = 25,
    RESNET50_LAYER_LAYER3_0_CONV3 = 26,
    RESNET50_LAYER_LAYER3_0_DOWNSAMPLE = 27,
    RESNET50_LAYER_LAYER3_1_CONV1 = 28,
    RESNET50_LAYER_LAYER3_1_CONV2 = 29,
    RESNET50_LAYER_LAYER3_1_CONV3 = 30,
    RESNET50_LAYER_LAYER3_2_CONV1 = 31,
    RESNET50_LAYER_LAYER3_2_CONV2 = 32,
    RESNET50_LAYER_LAYER3_2_CONV3 = 33,
    RESNET50_LAYER_LAYER3_3_CONV1 = 34,
    RESNET50_LAYER_LAYER3_3_CONV2 = 35,
    RESNET50_LAYER_LAYER3_3_CONV3 = 36,
    RESNET50_LAYER_LAYER3_4_CONV1 = 37,
    RESNET50_LAYER_LAYER3_4_CONV2 = 38,
    RESNET50_LAYER_LAYER3_4_CONV3 = 39,
    RESNET50_LAYER_LAYER3_5_CONV1 = 40,
    RESNET50_LAYER_LAYER3_5_CONV2 = 41,
    RESNET50_LAYER_LAYER3_5_CONV3 = 42,
    RESNET50_LAYER_LAYER4_0_CONV1 = 43,
    RESNET50_LAYER_LAYER4_0_CONV2 = 44,
    RESNET50_LAYER_LAYER4_0_CONV3 = 45,
    RESNET50_LAYER_LAYER4_0_DOWNSAMPLE = 46,
    RESNET50_LAYER_LAYER4_1_CONV1 = 47,
    RESNET50_LAYER_LAYER4_1_CONV2 = 48,
    RESNET50_LAYER_LAYER4_1_CONV3 = 49,
    RESNET50_LAYER_LAYER4_2_CONV1 = 50,
    RESNET50_LAYER_LAYER4_2_CONV2 = 51,
    RESNET50_LAYER_LAYER4_2_CONV3 = 52,
    RESNET50_LAYER_FC = 53,
    RESNET50_LAYER_COUNT = 54
} Resnet50LayerId;

// ---- Per-layer shape info + VWB2 tensor offsets ----
// weight_offset / bias_offset: byte offsets from WEIGHT_BLOB_ADDR
//   (i.e., absolute address = WEIGHT_BLOB_ADDR + offset)
// weight_bytes / bias_bytes: byte counts for each tensor payload
// weight_blocks: number of 18-byte BD blocks in the weight tensor
typedef struct {
    const char*  name;
    uint32_t     w_elements;
    uint32_t     b_elements;
    uint32_t     w_bd_blocks;
    uint32_t     weight_offset;  /* bytes from WEIGHT_BLOB_ADDR */
    uint32_t     weight_bytes;
    uint32_t     bias_offset;    /* bytes from WEIGHT_BLOB_ADDR */
    uint32_t     bias_bytes;
} Resnet50LayerInfo;

static const Resnet50LayerInfo RESNET50_LAYERS[54] = {
    /* conv1 */
    {"conv1", 9408u, 64u, 294u,
     0x00001100u, 5300u,
     0x000025B4u, 256u},
    /* layer1.0.conv1 */
    {"layer1.0.conv1", 4096u, 64u, 128u,
     0x000026B4u, 2312u,
     0x00002FBCu, 256u},
    /* layer1.0.conv2 */
    {"layer1.0.conv2", 36864u, 64u, 1152u,
     0x000030BCu, 20744u,
     0x000081C4u, 256u},
    /* layer1.0.conv3 */
    {"layer1.0.conv3", 16384u, 256u, 512u,
     0x000082C4u, 9224u,
     0x0000A6CCu, 1024u},
    /* layer1.0.downsample */
    {"layer1.0.downsample", 16384u, 256u, 512u,
     0x0000AACCu, 9224u,
     0x0000CED4u, 1024u},
    /* layer1.1.conv1 */
    {"layer1.1.conv1", 16384u, 64u, 512u,
     0x0000D2D4u, 9224u,
     0x0000F6DCu, 256u},
    /* layer1.1.conv2 */
    {"layer1.1.conv2", 36864u, 64u, 1152u,
     0x0000F7DCu, 20744u,
     0x000148E4u, 256u},
    /* layer1.1.conv3 */
    {"layer1.1.conv3", 16384u, 256u, 512u,
     0x000149E4u, 9224u,
     0x00016DECu, 1024u},
    /* layer1.2.conv1 */
    {"layer1.2.conv1", 16384u, 64u, 512u,
     0x000171ECu, 9224u,
     0x000195F4u, 256u},
    /* layer1.2.conv2 */
    {"layer1.2.conv2", 36864u, 64u, 1152u,
     0x000196F4u, 20744u,
     0x0001E7FCu, 256u},
    /* layer1.2.conv3 */
    {"layer1.2.conv3", 16384u, 256u, 512u,
     0x0001E8FCu, 9224u,
     0x00020D04u, 1024u},
    /* layer2.0.conv1 */
    {"layer2.0.conv1", 32768u, 128u, 1024u,
     0x00021104u, 18440u,
     0x0002590Cu, 512u},
    /* layer2.0.conv2 */
    {"layer2.0.conv2", 147456u, 128u, 4608u,
     0x00025B0Cu, 82952u,
     0x00039F14u, 512u},
    /* layer2.0.conv3 */
    {"layer2.0.conv3", 65536u, 512u, 2048u,
     0x0003A114u, 36872u,
     0x0004311Cu, 2048u},
    /* layer2.0.downsample */
    {"layer2.0.downsample", 131072u, 512u, 4096u,
     0x0004391Cu, 73736u,
     0x00055924u, 2048u},
    /* layer2.1.conv1 */
    {"layer2.1.conv1", 65536u, 128u, 2048u,
     0x00056124u, 36872u,
     0x0005F12Cu, 512u},
    /* layer2.1.conv2 */
    {"layer2.1.conv2", 147456u, 128u, 4608u,
     0x0005F32Cu, 82952u,
     0x00073734u, 512u},
    /* layer2.1.conv3 */
    {"layer2.1.conv3", 65536u, 512u, 2048u,
     0x00073934u, 36872u,
     0x0007C93Cu, 2048u},
    /* layer2.2.conv1 */
    {"layer2.2.conv1", 65536u, 128u, 2048u,
     0x0007D13Cu, 36872u,
     0x00086144u, 512u},
    /* layer2.2.conv2 */
    {"layer2.2.conv2", 147456u, 128u, 4608u,
     0x00086344u, 82952u,
     0x0009A74Cu, 512u},
    /* layer2.2.conv3 */
    {"layer2.2.conv3", 65536u, 512u, 2048u,
     0x0009A94Cu, 36872u,
     0x000A3954u, 2048u},
    /* layer2.3.conv1 */
    {"layer2.3.conv1", 65536u, 128u, 2048u,
     0x000A4154u, 36872u,
     0x000AD15Cu, 512u},
    /* layer2.3.conv2 */
    {"layer2.3.conv2", 147456u, 128u, 4608u,
     0x000AD35Cu, 82952u,
     0x000C1764u, 512u},
    /* layer2.3.conv3 */
    {"layer2.3.conv3", 65536u, 512u, 2048u,
     0x000C1964u, 36872u,
     0x000CA96Cu, 2048u},
    /* layer3.0.conv1 */
    {"layer3.0.conv1", 131072u, 256u, 4096u,
     0x000CB16Cu, 73736u,
     0x000DD174u, 1024u},
    /* layer3.0.conv2 */
    {"layer3.0.conv2", 589824u, 256u, 18432u,
     0x000DD574u, 331784u,
     0x0012E57Cu, 1024u},
    /* layer3.0.conv3 */
    {"layer3.0.conv3", 262144u, 1024u, 8192u,
     0x0012E97Cu, 147464u,
     0x00152984u, 4096u},
    /* layer3.0.downsample */
    {"layer3.0.downsample", 524288u, 1024u, 16384u,
     0x00153984u, 294920u,
     0x0019B98Cu, 4096u},
    /* layer3.1.conv1 */
    {"layer3.1.conv1", 262144u, 256u, 8192u,
     0x0019C98Cu, 147464u,
     0x001C0994u, 1024u},
    /* layer3.1.conv2 */
    {"layer3.1.conv2", 589824u, 256u, 18432u,
     0x001C0D94u, 331784u,
     0x00211D9Cu, 1024u},
    /* layer3.1.conv3 */
    {"layer3.1.conv3", 262144u, 1024u, 8192u,
     0x0021219Cu, 147464u,
     0x002361A4u, 4096u},
    /* layer3.2.conv1 */
    {"layer3.2.conv1", 262144u, 256u, 8192u,
     0x002371A4u, 147464u,
     0x0025B1ACu, 1024u},
    /* layer3.2.conv2 */
    {"layer3.2.conv2", 589824u, 256u, 18432u,
     0x0025B5ACu, 331784u,
     0x002AC5B4u, 1024u},
    /* layer3.2.conv3 */
    {"layer3.2.conv3", 262144u, 1024u, 8192u,
     0x002AC9B4u, 147464u,
     0x002D09BCu, 4096u},
    /* layer3.3.conv1 */
    {"layer3.3.conv1", 262144u, 256u, 8192u,
     0x002D19BCu, 147464u,
     0x002F59C4u, 1024u},
    /* layer3.3.conv2 */
    {"layer3.3.conv2", 589824u, 256u, 18432u,
     0x002F5DC4u, 331784u,
     0x00346DCCu, 1024u},
    /* layer3.3.conv3 */
    {"layer3.3.conv3", 262144u, 1024u, 8192u,
     0x003471CCu, 147464u,
     0x0036B1D4u, 4096u},
    /* layer3.4.conv1 */
    {"layer3.4.conv1", 262144u, 256u, 8192u,
     0x0036C1D4u, 147464u,
     0x003901DCu, 1024u},
    /* layer3.4.conv2 */
    {"layer3.4.conv2", 589824u, 256u, 18432u,
     0x003905DCu, 331784u,
     0x003E15E4u, 1024u},
    /* layer3.4.conv3 */
    {"layer3.4.conv3", 262144u, 1024u, 8192u,
     0x003E19E4u, 147464u,
     0x004059ECu, 4096u},
    /* layer3.5.conv1 */
    {"layer3.5.conv1", 262144u, 256u, 8192u,
     0x004069ECu, 147464u,
     0x0042A9F4u, 1024u},
    /* layer3.5.conv2 */
    {"layer3.5.conv2", 589824u, 256u, 18432u,
     0x0042ADF4u, 331784u,
     0x0047BDFCu, 1024u},
    /* layer3.5.conv3 */
    {"layer3.5.conv3", 262144u, 1024u, 8192u,
     0x0047C1FCu, 147464u,
     0x004A0204u, 4096u},
    /* layer4.0.conv1 */
    {"layer4.0.conv1", 524288u, 512u, 16384u,
     0x004A1204u, 294920u,
     0x004E920Cu, 2048u},
    /* layer4.0.conv2 */
    {"layer4.0.conv2", 2359296u, 512u, 73728u,
     0x004E9A0Cu, 1327112u,
     0x0062DA14u, 2048u},
    /* layer4.0.conv3 */
    {"layer4.0.conv3", 1048576u, 2048u, 32768u,
     0x0062E214u, 589832u,
     0x006BE21Cu, 8192u},
    /* layer4.0.downsample */
    {"layer4.0.downsample", 2097152u, 2048u, 65536u,
     0x006C021Cu, 1179656u,
     0x007E0224u, 8192u},
    /* layer4.1.conv1 */
    {"layer4.1.conv1", 1048576u, 512u, 32768u,
     0x007E2224u, 589832u,
     0x0087222Cu, 2048u},
    /* layer4.1.conv2 */
    {"layer4.1.conv2", 2359296u, 512u, 73728u,
     0x00872A2Cu, 1327112u,
     0x009B6A34u, 2048u},
    /* layer4.1.conv3 */
    {"layer4.1.conv3", 1048576u, 2048u, 32768u,
     0x009B7234u, 589832u,
     0x00A4723Cu, 8192u},
    /* layer4.2.conv1 */
    {"layer4.2.conv1", 1048576u, 512u, 32768u,
     0x00A4923Cu, 589832u,
     0x00AD9244u, 2048u},
    /* layer4.2.conv2 */
    {"layer4.2.conv2", 2359296u, 512u, 73728u,
     0x00AD9A44u, 1327112u,
     0x00C1DA4Cu, 2048u},
    /* layer4.2.conv3 */
    {"layer4.2.conv3", 1048576u, 2048u, 32768u,
     0x00C1E24Cu, 589832u,
     0x00CAE254u, 8192u},
    /* fc */
    {"fc", 2048000u, 1000u, 64000u,
     0x00CB0254u, 1152008u,
     0x00DC965Cu, 4000u},
};

#endif /* RESNET50_MODEL_CONSTANTS_H */
