// AUTO-GENERATED by quantized_reference.py — do not edit
// Integer quantized reference (shift=7)

#ifndef RESNET50_QUANTIZED_REF_H
#define RESNET50_QUANTIZED_REF_H

#include <stdint.h>

#define QUANT_REF_SHIFT  7
#define QUANT_REF_TOP1   -1

// Per-stage activation hashes (sum-of-int8, uint32)
#define QUANT_REF_HASH_CONV1  0x00000000u
#define QUANT_REF_HASH_STEM_POOL  0x00000000u

// Top-5 predictions
static const int QUANT_REF_TOP5[5] = {  };

#endif /* RESNET50_QUANTIZED_REF_H */
