// AUTO-GENERATED by gen_resnet1202_model.py — do not edit
// Model: resnet1202_cifar10
// FP32 golden reference (no quantization)

#ifndef RN1202_EXPECTED_FP32_H
#define RN1202_EXPECTED_FP32_H

#include <stdint.h>

#define EXPECTED_TOP1_CLASS   2
#define EXPECTED_TRUE_LABEL   -1
// Top-1 class name: bird
// True label name : unknown
#define EXPECTED_LOGITS_SHA256 "198d5d2aeb0ac566858c36b1fcc3b7c8815633aef74ddfc01b172924cba30c62"
#define EXPECTED_LOGITS_U32SUM  0x002662D2u

const int32_t  EXPECTED_TOP5_IDX[5]   = { 2, 3, 7, 9, 4 };
const float    EXPECTED_TOP5_LOGIT[5] = { 12.623123f, 6.165370f, 3.032136f, 0.529024f, 0.013253f };

// Full logit array (FP32, 10 classes)
const float EXPECTED_LOGITS[10] = {
    -5.306060f,    -7.245573f,    12.623123f,    6.165370f,    0.013253f,
    -1.776788f,    -3.905048f,    3.032136f,    -4.171536f,    0.529024f,

};

#endif /* RN1202_EXPECTED_FP32_H */
