// AUTO-GENERATED by scripts/rn1202_ref.py — do not edit
// ResNet-1202 CIFAR-10 BD4-faithful reference
// Checksums = raw uint8 byte-sum of BD4 buffers,
// matching print_bd4_cksum() in resnet1202_conv.h.

#ifndef RN1202_QUANTIZED_REF_H
#define RN1202_QUANTIZED_REF_H

#include <stdint.h>

#define RN1202_REF_TOP1  0

// Per-stage BD4 buffer byte-sums
#define RN1202_BD4_CKSUM_CONV1  0x000493DEu
#define RN1202_BD4_CKSUM_STAGE1  0x000688A4u
#define RN1202_BD4_CKSUM_STAGE2  0x0000F000u
#define RN1202_BD4_CKSUM_STAGE3  0x00007800u

#endif /* RN1202_QUANTIZED_REF_H */
