// AUTO-GENERATED by quantized_reference.py --model rn1202 — do not edit
// ResNet-1202 CIFAR-10: paper-faithful BD4 activation path
// Checksums are raw uint8 byte-sum of BD4 buffers,
// matching firmware print_bd4_cksum() in resnet1202_phase3_hw_decode.

#ifndef RN1202_QUANTIZED_REF_H
#define RN1202_QUANTIZED_REF_H

#include <stdint.h>

#define RN1202_BD4_TOP1    0

// Per-stage calibrated output shifts (from calibrate_rn1202_shifts)
// shift = max(0, floor(log2(max_accum)) - 6) per layer,
// then collapsed to per-stage max.
#define RN1202_SHIFT_STEM    2
#define RN1202_SHIFT_STAGE1  0
#define RN1202_SHIFT_STAGE2  0
#define RN1202_SHIFT_STAGE3  0

// Raw BD4 buffer byte-sums at stage boundaries
#define RN1202_BD4_CKSUM_CONV1  0x0005CF1Au
#define RN1202_BD4_CKSUM_STAGE1  0x0006B56Eu
#define RN1202_BD4_CKSUM_STAGE2  0x0002B3FCu
#define RN1202_BD4_CKSUM_STAGE3  0x00013670u

#endif /* RN1202_QUANTIZED_REF_H */
